### ISSUE TITLE
issue with zabbix 5.0

### ISSUE THREAD

**Issue by sweetnight19** [RobinR1/zbx-template-zypper-updateinfo#1]
I know the minium version are 5.2 but is it possible to make it enable with 5.0 xml format?

**Comment by RobinR1** [comment]
You can try with this: [template_module_zypper_updateinfo.zip](https://github.com/RobinR1/zbx-template-zypper-updateinfo/files/7285076/template_module_zypper_updateinfo.zip)
(exported it as .XML in v5.2 and changed version number inside XML to 5.0. No guarantee that it will actually work in 5.0.)

**Comment by sweetnight19** [comment]
Hi again, i have this log in zabbix when i import the new template, i saw version 5.0 write it:

Invalid tag "/zabbix_export/templates/template(1)/items/item(1)/preprocessing/step(1)": unexpected tag "parameters".

![Captura](https://user-images.githubusercontent.com/24542429/136165413-f64c63b0-5ed4-4b8b-9671-353774475664.PNG)

**Comment by RobinR1** [comment]
I'm sorry. But I can't help with that; I currently don't have a zabbix 5.0 installation to play with that. Possibly something changed in the export format between 5.0 and 5.2. You could try to load the template in an 5.2 installation yourself, and replicate the functionality of the template in a 5.0 installation by hand. (Or try to replicate it by just reading/interpreting the XML yourself)
