### ISSUE TITLE
convert to python 3.4 

### ISSUE THREAD

**Issue by sweetnight19** [RobinR1/zbx-template-zypper-updateinfo#2]
Hi again sir,

in your script i saw that works fine with python 3.4 but show me syntax error:

![Captura](https://user-images.githubusercontent.com/24542429/136351816-adc25303-7350-4137-97e2-230821d3dcba.PNG)

**Comment by RobinR1** [comment]
Indeed, I overlooked the fact that f-strings are only supported since Python 3.6.
Could you try a4bb3c2fd40e24be02792935135f5a33d3a88a4a ?

**Comment by sweetnight19** [comment]
i solved making a printf("{}....".format(<varName>))
